Tidy up variables

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -25,24 +25,25 @@ ui_print "########################################";
 ui_print " ";
 
 # /dev/tmp is safe for both booted and recovery installs
-tmp=/dev/tmp/twrp-install;
+TMP=/dev/tmp/twrp-install;
+
 # target partition without the slot suffix
 if [ -e /dev/block/bootdevice/by-name/recovery_b ]; then
-  target=/dev/block/bootdevice/by-name/recovery;
+  TARGET=/dev/block/bootdevice/by-name/recovery;
 else
-  target=/dev/block/bootdevice/by-name/boot;
+  TARGET=/dev/block/bootdevice/by-name/boot;
 fi;
-name=$(basename $target);
+NAME=$(basename $TARGET);
 
 ui_print "Unpacking the installer...";
-rm -rf $tmp;
-mkdir -p $tmp;
-unzip -o "$ZIPFILE" -d $tmp || abort "Failed to extract zip!";
+rm -rf $TMP;
+mkdir -p $TMP;
+unzip -o "$ZIPFILE" -d $TMP || abort "Failed to extract zip!";
 
-cd $tmp;
-recoverycpio=`(ls ramdisk-twrp.cpio || ls ramdisk-recovery.cpio) 2>/dev/null`;
-recoveryimg=`(ls twrp*.img || ls TWRP*.img || ls recovery.img) 2>/dev/null`;
-[ "$recoverycpio" ] || [ "$recoveryimg" ] || abort "No TWRP ramdisk/image found in zip!";
+cd $TMP;
+RECOVERYCPIO=`(ls ramdisk-twrp.cpio || ls ramdisk-recovery.cpio) 2>/dev/null`;
+RECOVERYIMG=`(ls twrp*.img || ls TWRP*.img || ls recovery.img) 2>/dev/null`;
+[ "$RECOVERYCPIO" ] || [ "$RECOVERYIMG" ] || abort "No TWRP ramdisk/image found in zip!";
 
 chmod 755 magiskboot-arm*;
 if ./magiskboot-arm64 cleanup 2>/dev/null; then
@@ -51,37 +52,36 @@ else
   mv -f magiskboot-arm magiskboot;
 fi;
 rm -f magiskboot-arm*;
-tool=./magiskboot;
 
 ui_print " ";
-for slot in _a _b; do
-  if [ "$recoverycpio" ]; then
-    ui_print "Running image patcher on $name$slot...";
-    dd bs=1048576 if=$target$slot of=boot.img || abort "Failed to dump image!";
-    $tool unpack -h boot.img || abort "Failed to unpack image!";
+for SLOT in _a _b; do
+  if [ "$RECOVERYCPIO" ]; then
+    ui_print "Running image patcher on $NAME$SLOT...";
+    dd bs=1048576 if=$TARGET$SLOT of=boot.img || abort "Failed to dump image!";
+    ./magiskboot unpack -h boot.img || abort "Failed to unpack image!";
 
     # kernel string want_initramfs -> skip_initramfs (Magisk)
-    $tool hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
+    ./magiskboot hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
     # kernel string trip_initramfs -> skip_initramfs (SuperSU)
-    $tool hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;
+    ./magiskboot hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;
 
     # boot.img header cmdline remove skip_override (flar2 patch)
     sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;
 
-    cp -f $recoverycpio ramdisk.cpio;
-    $tool repack boot.img || abort "Failed to repack image!";
-    $tool cleanup;
+    cp -f $RECOVERYCPIO ramdisk.cpio;
+    ./magiskboot repack boot.img || abort "Failed to repack image!";
+    ./magiskboot cleanup;
   else
     ui_print "Flashing image to $name$slot...";
-    cp -f $recoveryimg new-boot.img;
+    cp -f $RECOVERYIMG new-boot.img;
   fi;
 
-  blockdev --setrw $target$slot;
-  cat new-boot.img /dev/zero > $target$slot 2>/dev/null || true;
+  blockdev --setrw $TARGET$SLOT;
+  cat new-boot.img /dev/zero > $TARGET$SLOT 2>/dev/null || true;
   rm -f new-boot.img;
 done;
 
-if [ "$recoverycpio" ]; then
+if [ "$RECOVERYCPIO" ]; then
   ui_print " ";
   ui_print "Image patching complete!";
 fi;
@@ -91,7 +91,7 @@ rm -rf /dev/tmp;
 
 ui_print " ";
 ui_print "Done installing TWRP!";
-if [ "$name" != "recovery" ]; then
+if [ "$NAME" != "recovery" ]; then
   ui_print " ";
   ui_print "*** NOTE: You are now unrooted! ***";
 fi;
