Latest template improvements - update magiskboot to v20.4-ed58cf95(20304) canary - add support for replacing recovery_a/recovery_b partition ramdisks on newer 2SI SAR A/B devices (e.g. OnePlus 7T), which obviously aren't boot-as-recovery but still benefit from being able to flash TWRP via zip for stock ROM post-OTA use - add more error catching from image dumping and magiskboot operations

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -20,7 +20,12 @@ ui_print " ";
 # /dev/tmp is safe for both booted and recovery installs
 tmp=/dev/tmp/twrp-install;
 # target partition without the slot suffix
-target=/dev/block/bootdevice/by-name/boot;
+if [ -e /dev/block/bootdevice/by-name/recovery_b ]; then
+  target=/dev/block/bootdevice/by-name/recovery;
+else
+  target=/dev/block/bootdevice/by-name/boot;
+fi;
+name=$(basename $target);
 
 ui_print "Unpacking the installer...";
 ui_print " ";
@@ -29,17 +34,16 @@ mkdir -p $tmp;
 unzip -o "$ZIPFILE" -d $tmp || abort "Failed to extract zip!";
 
 cd $tmp;
-tool=$tmp/magiskboot;
 recoverycpio=`(ls ramdisk-twrp.cpio || ls ramdisk-recovery.cpio) 2>/dev/null`;
 test "$recoverycpio" || abort "No TWRP ramdisk cpio found!";
 
+tool=$tmp/magiskboot;
 chmod 755 $tool;
 
-for slot in a b; do
-  ui_print "Running boot image patcher on slot $slot...";
-  slot=_$slot;
-  dd bs=1048576 if=$target$slot of=boot.img;
-  $tool unpack -h boot.img;
+for slot in _a _b; do
+  ui_print "Running image patcher on $name$slot...";
+  dd bs=1048576 if=$target$slot of=boot.img || abort "Failed to dump image!";
+  $tool unpack -h boot.img || abort "Failed to unpack image!";
 
   # kernel string want_initramfs -> skip_initramfs (Magisk)
   $tool hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
@@ -50,7 +54,7 @@ for slot in a b; do
   sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;
 
   cp -f $recoverycpio ramdisk.cpio;
-  $tool repack boot.img;
+  $tool repack boot.img || abort "Failed to repack image!";
   cat new-boot.img /dev/zero > $target$slot 2>/dev/null || true;
 
   $tool cleanup;
@@ -58,12 +62,14 @@ for slot in a b; do
 done;
 
 ui_print " ";
-ui_print "Boot image patching complete!";
+ui_print "Image patching complete!";
 
 cd /;
 rm -rf /dev/tmp;
 
 ui_print " ";
 ui_print "Done installing TWRP!";
-ui_print " ";
-ui_print "*** NOTE: You are now unrooted! ***";
+if [ "$name" != "recovery" ]; then
+  ui_print " ";
+  ui_print "*** NOTE: You are now unrooted! ***";
+fi;
